import type { Data as EjsData } from 'ejs';
import { Questions } from '../types';

/**
 * Merges multiple `Questions` into one, flattened array.
 */

/* eslint-disable prettier/prettier */
export function mergePrompts<A extends EjsData>(...questions: [Questions<A>]): Questions<A>;
export function mergePrompts<A extends EjsData, B extends EjsData>(...questions: [Questions<A>, Questions<B>]): Questions<A & B>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>]): Questions<A & B & C>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>]): Questions<A & B & C & D>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>]): Questions<A & B & C & D & E>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>]): Questions<A & B & C & D & E & F>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>]): Questions<A & B & C & D & E & F & G>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>]): Questions<A & B & C & D & E & F & G & H>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>]): Questions<A & B & C & D & E & F & G & H & I>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>]): Questions<A & B & C & D & E & F & G & H & I & J>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>]): Questions<A & B & C & D & E & F & G & H & I & J & K>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData, V extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>, Questions<V>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U & V>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData, V extends EjsData, W extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>, Questions<V>, Questions<W>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U & V & W>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData, V extends EjsData, W extends EjsData, X extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>, Questions<V>, Questions<W>, Questions<X>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U & V & W & X>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData, V extends EjsData, W extends EjsData, X extends EjsData, Y extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>, Questions<V>, Questions<W>, Questions<X>, Questions<Y>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U & V & W & X & Y>;
export function mergePrompts<A extends EjsData, B extends EjsData, C extends EjsData, D extends EjsData, E extends EjsData, F extends EjsData, G extends EjsData, H extends EjsData, I extends EjsData, J extends EjsData, K extends EjsData, L extends EjsData, M extends EjsData, N extends EjsData, O extends EjsData, P extends EjsData, Q extends EjsData, R extends EjsData, S extends EjsData, T extends EjsData, U extends EjsData, V extends EjsData, W extends EjsData, X extends EjsData, Y extends EjsData, Z extends EjsData>(...questions: [Questions<A>, Questions<B>, Questions<C>, Questions<D>, Questions<E>, Questions<F>, Questions<G>, Questions<H>, Questions<I>, Questions<J>, Questions<K>, Questions<L>, Questions<M>, Questions<N>, Questions<O>, Questions<P>, Questions<Q>, Questions<R>, Questions<S>, Questions<T>, Questions<U>, Questions<V>, Questions<W>, Questions<X>, Questions<Y>, Questions<Z>]): Questions<A & B & C & D & E & F & G & H & I & J & K & L & M & N & O & P & Q & R & S & T & U & V & W & X & Y & Z>;
/* eslint-enable prettier/prettier */

export function mergePrompts(...questions: Questions<any>[]): Questions<any> {
  const result: Questions<any> = [];

  questions.forEach((q) => {
    if (Array.isArray(q)) {
      result.push(...q);
    } else {
      result.push(q);
    }
  });

  return result;
}
